Develop/MVC/MVC56/cursos 2022 udemy/ManejoPresupuesto/ManejoPresupuesto/Controllers/TiposCuentasController.cs
using Dapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace ManejoPresupuesto.Controllers
{
    public class TiposCuentasController : Controller
    {

        //esto es para probar la conexion a datos con dapper: se crea la instancia en el constructor
        //y luego en crear se llama a la libreria de dapper. pero es una forma provisional ya que el
        //codigo de acceso a datos no debe ir en el controlador. se debe cear una clase repositorio,
        //dentro de una carpeta servicios.

        //private readonly string cn;
        //public TiposCuentasController(IConfiguration configuration)
        //{
        //    cn = configuration.GetConnectionString("DefaultConnection");
        //}


        //esto es para cuando se utiliza el repositorio con interfaces
        private IRepositorioTiposCuentas RepositorioTiposCuentas;
        private readonly IServicioUsuarios servicioUsuarios;


        //agregamos el servicio de usuarioId en el constructor y se agrega como
        //campo
        public TiposCuentasController(IRepositorioTiposCuentas repositorioTiposCuentas, IServicioUsuarios servicioUsuarios)
        {
            this.RepositorioTiposCuentas = repositorioTiposCuentas;
            this.servicioUsuarios = servicioUsuarios;
        }


        public async Task<IActionResult> Index()
        {
            //de aqui se debe crear la vista para mostrar la lista
            //se va sustituyendo var usuarioId=1;

            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tiposcuentas = await RepositorioTiposCuentas.Obtener(usuarioId);
            return View(tiposcuentas);
        }

        public IActionResult crear()
        {
            //codigo para probar dapper
            //using (var connection=new SqlConnection(cn))
            //{
            //    var qry = connection.Query("SELECT 1").FirstOrDefault();
            //}

            //ejemplo de como mandar un dato dentro del modelo
            //var mod = new TipoCuenta() { nombre = "adan" };
            //return View(mod);
            return View("crear");
        }

        [HttpPost]
        /*[ValidateAntiForgeryToken]*/
        /*OJO. mandaba el parametro pero no como instancia del modelo, agregando method="post"
         * a la propiedad del formaulario en la vista, ahora si se instancia el modelo Tipos 
         * Cuentas, solo que los campos siguen llegando nulos.
         * 
         * una alternativa era la coleccion FormCollection
         * 
         * pasaba nulo tc porque se estaban utilizanco como campos las propiedades del modelo
         */
        public async Task<IActionResult> crear(TipoCuenta tc) //FormCollection fc)//
        {
            /*aunque hay validacion de campos en la vista, requiere cachar la validez del modelo*/

            if (!ModelState.IsValid)
            {
                /*se le manda tc para que se siga viendo la informacion que ya tenia capturada,
                 persiste la data del formulario, ver asp-for en la vista*/
                return View(tc);
            }

            //aqui ya se puede utilizar el procedimiento crear
            //se le da un usuarioid artificial porque aun no se crea el procedimiento
            tc.usuarioid = servicioUsuarios.ObtenerUsuarioId();

            //aqui la otra parte de la validacion para ver si existe el tipo de cuenta
            var yaExiste = await RepositorioTiposCuentas.Existe(tc.nombre, tc.usuarioid);
            if (yaExiste)
            {
                ModelState.AddModelError(nameof(tc.nombre), $"el {tc.nombre} ya existe");
                return View(tc);
            }


            await RepositorioTiposCuentas.Crear(tc);

            //como ya existe un index debe redirigir ahi, no al success
            //sin redirecttoaction mandaba error al llamar a Model de la vista ??????, quiza redirect llama a la vista desde una instancia ya existente
            return RedirectToAction("index");
        }



        //editar, aqui realmente busca el usuario por id
        [HttpGet]
        public async Task<ActionResult> Editar(int id)
        {
            //comprueba los ids
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await RepositorioTiposCuentas.ObtenerXId(id, usuarioId);

            if (tipoCuenta is null) {
                return RedirectToAction("noencontrado", "" +
                    "Home");
            }

            //si vienen los ides llama al formulario de edicion SOLO LLAMA AL FORMULARIO PARA EDITAR
            return View(tipoCuenta);
        }


        //en este si se hace la edicion de datos
        [HttpPost]
        public async Task<ActionResult> Editar(TipoCuenta tipoCuenta)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuentaExiste = await RepositorioTiposCuentas.ObtenerXId(tipoCuenta.id,usuarioId);

            if(tipoCuentaExiste is null)
            {
                return RedirectToAction("noencontrado","Home");
            }

            //este es realmente la diferencia. aqui se le mandan los datos del modelo MANDA LOS DATOS EDITADOS
            await RepositorioTiposCuentas.Actualizar(tipoCuenta);
            return RedirectToAction("index");
        }


        //validaciones por controlador. ???? son validaciones que utilizan js, a fin de cuentas
        //llaman al procedimiento Existe y tambien PIENSO que se viola el pincipio
        //de duplicar funcionalidad del controlador
        //luego se invoca el atributo en el modelo

        [HttpGet]
        public async Task<IActionResult> VerificarTCuenta(string nombre)
        {
            //se debe tomar el id de usuario de alguna lista
            var usuarioid = servicioUsuarios.ObtenerUsuarioId();
            var YaExiste = await RepositorioTiposCuentas.Existe(nombre, usuarioid);

            if(YaExiste)
            {
                return Json($"el nombre {nombre} ya existe");
            }

            return Json(true);
        }

        //evalua que los ides sean validos
        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await RepositorioTiposCuentas.ObtenerXId(id,usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("noencontrado","Home");

            }
            return View(tipoCuenta);

        }


        //el procedimiento que realmente borra, notar que no es sobrecarga, por ello si 
        //cambia de nombre. aqui se debe crear la vista, el formulario de confirmacion
        [HttpPost]
        public async Task<IActionResult> BorraTC(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await RepositorioTiposCuentas.ObtenerXId(id, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("noencontrado", "Home");

            }
            await RepositorioTiposCuentas.Borrar(id);
            return RedirectToAction("index");
        }
        
       

    }
}

Develop/MVC/MVC56/cursos 2022 udemy/ManejoPresupuesto/ManejoPresupuesto/Views/TiposCuentas/borrar.cshtml
@model TipoCuenta

@{
    ViewData["Title"] = "Borrar el tipod e cuenta";
}

<h3 mb-3>Seguro que desea borrar?</h3>


<!--de qui a modificar el boton de borrado del index-->
<form asp-action="BorraTC">
    <input type="hidden" asp-for="id"/>
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-secondary" asp-action="index">Cancelar</a>
</form>

Develop/MVC/MVC56/cursos 2022 udemy/ManejoPresupuesto/ManejoPresupuesto/Views/TiposCuentas/crear.cshtml
@model TipoCuenta

@{

    ViewData["Title"] = "Crear tipo cuenta";
}

<h5>Tipos de cuentas</h5>
<h3>Formulario</h3>

<div asp-validation-summary="ModelOnly" class="text-danger">
    <!--solo que cache los errores del modelo, no todos-->

</div>

<!--se obvia la llamada al controlador porque lo busca por default, tiene el mismo nombre-->
<form asp-action="crear" >

    <!--@Html.AntiForgeryToken()-->

    <div class="mb-3">

        <!--con ASP-FOR, junto con el modelo como argumento, haran que la data capturada no se borre, en caso de haber error
            hasta el caption se quita
        -->
       <label asp-for="nombre" class="col-form-label">Nombre</label>
       <!--<input type="text" id="nombre" name="nombre" class="form-control"/>  por esta otra opcion de codigo embebido:
            @Html.TextBoxFor(x => x.nombre,
               new { @class = "form-control", placeholder = "pon el nombre", autofocus = "autofocus" })
            @Html.ValidationMessageFor(x => x.nombre, null, new { @class = "text-danger" })
       -->
       
       <input type="text" asp-for="nombre" class="form-control"/>
       <span asp-validation-for="nombre" class="text-danger"> </span>

       <!--
           cuando las validaciones son muy especificas, hay que crearlas, se hace con una crpeta y dentro una clase de c# que herede
           de validationatribute, hay que crear los procedimientos manualmente
       -->


     




       <!--campos de prueba para ver validaciones, notar que con asp-for se simplifica
           pues esta vinculado al modelo.

           Se usan otras validaciones porque las de los data annotation no son suficientes, 
           siempre salen otros detalles que controlar. 
           para validacion con jquery se le pone un span debajo del control
      
       <div class="mb-3">
            <label asp-for="Email" class="col-form-label"></label>
            <input type="text" asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"> </span>
        </div>

         <div class="mb-3">
            <label asp-for="Edad" class="col-form-label"></label>
            <input type="text" asp-for="Edad" class="form-control"/>
             <span asp-validation-for="Edad" class="text-danger"> </span>
        </div>

         <div class="mb-3">
            <label asp-for="URL" class="col-form-label"></label>
            <input type="text" asp-for="URL" class="form-control"/>
             <span asp-validation-for="URL" class="text-danger"> </span>
        </div>

         <div class="mb-3">
            <label asp-for="TarjetaCredito" class="col-form-label"></label>
            <input type="text" asp-for="TarjetaCredito" class="form-control"/>
             <span asp-validation-for="TarjetaCredito" class="text-danger"> </span>
        </div>   -->
       
    </div>




     <button type="submit" class="btn btn-primary">Enviar</button>
     <a class="btn btn-secondary" asp-action="Index">Cancelar</a>

</form>

<!----
se pueden incluir scrpts, pero deben ir al final, hay que agregar la referencia a jquery, esta en shared _validationscriptspartial
con eso se ponen las validaciones bajo cada campo. OJO, todas estas validaciones se ejecutan ANTES que la llamada al controlador,
lo cual es una llamada al servidor. Esta ultima se realiza si jquery pasa

-->

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

Develop/MVC/MVC56/cursos 2022 udemy/ManejoPresupuesto/ManejoPresupuesto/Views/TiposCuentas/editar.cshtml
@model TipoCuenta


@{
    ViewData["Title"] = "Editar tipos cuentas";
}

<h1>Editar tipo de cuenta</h1>

<!--aqui se copia el html de crear, y luego se le agregan cosas
    tambien se podrian hacer vistas parciales
-->


<div asp-validation-summary="ModelOnly" class="text-danger">
</div>

<form asp-action="Editar" >

    <div class="mb-3">
        <!--la linea que se agrega el id pero escondido, para otras acciones-->
      <input type="hidden" asp-for="id"/>

       <label asp-for="nombre" class="col-form-label">Nombre</label>
           
       <input type="text" asp-for="nombre" class="form-control"/>
       <span asp-validation-for="nombre" class="text-danger"> </span>
       
    </div>

     <button type="submit" class="btn btn-primary">Enviar</button>
     <a class="btn btn-secondary" asp-action="Index">Cancelar</a>

</form>



@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

Develop/MVC/MVC56/cursos 2022 udemy/ManejoPresupuesto/ManejoPresupuesto/Views/TiposCuentas/index.cshtml
@model IEnumerable<TipoCuenta>


@{
    ViewData["Title"] = "Tipos cuentas";
}

<h1>Tipos de cuentas</h1>
<h5>Ejem: préstamos, tarjetas, etc</h5>

<a asp-action="Crear" classaccesskey="btn btn-primary mb-3">Crear nuevo</a>

<table class="table">

    <thead>
        <tr>
            <th>Acciones</th>
            <th>Nombre</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var tipoCuenta in Model)
        {
                    
            <tr>
                <td>
                    <!--desde aqui se llama al procedimiento para editar-->
                    <a class="btn btn-primary" asp-action="Editar" asp-route-id="@tipoCuenta.id">Editar</a>
                    <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@tipoCuenta.id">Borrar</a>
                </td>
                <td>
                    @tipoCuenta.nombre
                </td>
            </tr>         

        }
    </tbody>

</table>

Develop/MVC/MVC56/cursos 2022 udemy/ManejoPresupuesto/ManejoPresupuesto/Views/TiposCuentas/success.cshtml
@{
   ViewData["Title"] = "Transacción existosa";
}
<h2>Crear nuevo tipo de cuenta</h2>
<br />
<h4>Congratulations, your transaction has been successful !!</h4>
<br />



<a class="nav-link border-bottom" asp-area="" asp-controller="TiposCuentas" asp-action="Crear">Crear tipo de cuenta nuevo</a>

Develop/MVC/MVC56/cursos 2022 udemy/ManejoPresupuesto/ManejoPresupuesto/Views/TiposCuentas/vistaprueba.cshtml
@{

    ViewData["Title"] = "Vista de prueba";
}

<h5>Soy una vista de prueba</h5>